// رموز الصلاحيات - يجب أن تطابق السيرفر (seedPermissions)
export const PERMISSIONS = {
    DASHBOARD_VIEW: "DASHBOARD_VIEW",
    DEPARTMENTS_VIEW: "DEPARTMENTS_VIEW",
    DEPARTMENTS_CREATE: "DEPARTMENTS_CREATE",
    DEPARTMENTS_UPDATE: "DEPARTMENTS_UPDATE",
    DEPARTMENTS_DELETE: "DEPARTMENTS_DELETE",
    STUDENTS_VIEW: "STUDENTS_VIEW",
    STUDENTS_CREATE: "STUDENTS_CREATE",
    STUDENTS_UPDATE: "STUDENTS_UPDATE",
    STUDENTS_DELETE: "STUDENTS_DELETE",
    COURSES_VIEW: "COURSES_VIEW",
    COURSES_CREATE: "COURSES_CREATE",
    COURSES_UPDATE: "COURSES_UPDATE",
    COURSES_DELETE: "COURSES_DELETE",
    ENROLLMENTS_VIEW: "ENROLLMENTS_VIEW",
    ENROLLMENTS_CREATE: "ENROLLMENTS_CREATE",
    ENROLLMENTS_UPDATE: "ENROLLMENTS_UPDATE",
    ENROLLMENTS_DELETE: "ENROLLMENTS_DELETE",
    USERS_VIEW: "USERS_VIEW",
    USERS_CREATE: "USERS_CREATE",
    USERS_UPDATE: "USERS_UPDATE",
    USERS_DELETE: "USERS_DELETE",
    PERMISSIONS_VIEW: "PERMISSIONS_VIEW",
    PERMISSIONS_CREATE: "PERMISSIONS_CREATE",
    PERMISSIONS_ASSIGN: "PERMISSIONS_ASSIGN",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
